package org.deichor.ktaleui.property

import org.deichor.ktaleui.enums.DropdownBoxAlign

data class DropdownBoxStyle(
    var defaultBackground: Any? = null,
    var hoveredBackground: Any? = null,
    var pressedBackground: Any? = null,
    var disabledBackground: Any? = null,
    var iconTexturePath: String? = null,
    var iconWidth: Int? = null,
    var iconHeight: Int? = null,
    var defaultArrowTexturePath: String? = null,
    var hoveredArrowTexturePath: String? = null,
    var pressedArrowTexturePath: String? = null,
    var disabledArrowTexturePath: String? = null,
    var arrowWidth: Int? = null,
    var arrowHeight: Int? = null,
    var horizontalPadding: Int? = null,
    var labelStyle: LabelStyle? = null,
    var disabledLabelStyle: LabelStyle? = null,
    var sounds: DropdownBoxSounds? = null,
    var panelTitleLabelStyle: LabelStyle? = null,
    var entryHeight: Int? = null,
    var entriesInViewport: Int? = null,
    var horizontalEntryPadding: Int? = null,
    var entryIconHeight: Int? = null,
    var entryIconWidth: Int? = null,
    var entryIconBackground: Any? = null,
    var selectedEntryIconBackground: Any? = null,
    var entryLabelStyle: LabelStyle? = null,
    var selectedEntryLabelStyle: LabelStyle? = null,
    var noItemsLabelStyle: LabelStyle? = null,
    var hoveredEntryBackground: Any? = null,
    var pressedEntryBackground: Any? = null,
    var focusOutlineSize: Int? = null,
    var focusOutlineColor: String? = null,
    var entrySounds: ButtonSounds? = null,
    var panelScrollbarStyle: ScrollbarStyle? = null,
    var panelBackground: Any? = null,
    var panelPadding: Int? = null,
    var panelAlign: DropdownBoxAlign? = null,
    var panelOffset: Int? = null,
    var panelWidth: Int? = null,
    var searchInputStyle: DropdownBoxSearchInputStyle? = null,
)
